package com.github.phalexei.fallingBlocks.Game;

import com.github.phalexei.fallingBlocks.Rendering.IRenderable;

public class GameUI implements IRenderable {
    @Override
    public void render(int tick) {
        //TODO: autogenerated stub
    }

    public void addScore(int points) {
        //TODO: autogenerated stub
    }
}
